[package]
name = "bean"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.68"
topo = "0.13.0"
moxie = "0.7.0"
console_error_panic_hook = "0.1.6"
