extend = "./default_makefile.toml"

[tasks.in_examples]
description = '''
Run chosen task for each example in its root.
Ex: 'makers in_examples mzoon -- -V' or `makers in_examples mzoon build"
'''
script = [
'''
#!@duckscript
handle = glob_array examples/*/Makefile.toml
args_string = array_join ${@} " "

for path in ${handle}
    example_root = dirname ${path}
    echo Example root: ${example_root}
    exec --fail-on-error makers --cwd ${example_root} %{args_string}
end
'''
]
