extend = "./default_makefile.toml"

[tasks.in_examples]
description = '''
Run chosen task for each example in its root.
Ex: 'makers in_examples mzoon -- -V' or `makers in_examples mzoon build"
'''
script = [
'''
#!@duckscript
handle = glob_array examples/*/Makefile.toml
for path in ${handle}
    example_root = dirname ${path}
    echo Example root: ${example_root}
    if is_defined 5
        exec --fail-on-error makers --cwd ${example_root} ${1} ${2} ${3} ${4} ${5}
    elseif is_defined 4
        exec --fail-on-error makers --cwd ${example_root} ${1} ${2} ${3} ${4}
    elseif is_defined 3
        exec --fail-on-error makers --cwd ${example_root} ${1} ${2} ${3}
    elseif is_defined 2
        exec --fail-on-error makers --cwd ${example_root} ${1} ${2}
    elseif is_defined 1
        exec --fail-on-error makers --cwd ${example_root} ${1}
    else
        exec --fail-on-error makers --cwd ${example_root}
    end
end
'''
]
