[package]
name = "mzoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
structopt = "0.3"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
notify = "4.0.12"
ctrlc = "3.1.8"
reqwest = { version = "0.11.1", features = ["blocking"] }
rcgen = "0.8.9"
open = "1"
