[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
extism-pdk = { git =  "https://github.com/extism/rust-pdk.git", rev = "6cd1f32eff116e5904e3481419f611dff590defc", default-features = false }



