[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
bincode = { version = "1.3.3", default-features = false }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
