[package]
name = "moon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.3"
warp = { version = "0.3", features = ["tls"] }
futures = "0.3.13"
uuid = { version = "0.8", features = ["v4"] }
