[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
# extism = { version = "=0.0.1-rc.6", default-features = false }
# extism = { git = "https://github.com/extism/extism.git", rev = "58ad4ce6e29c21ae3321d4732da18fa758ad1dfb", default-features = false }
extism = { path = "../../../../extism/rust", default-features = false }
extism-runtime = { path = "../../../../extism/runtime", default-features = false }
