[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
anyhow = { version = "1.0.66", features = ["std"], default-features = false }
# wasmer = { version = "v3.0.0", features = ["js", "std"], default-features = false }
wasmer = { path = "../../../../wasmer/lib/api", features = ["js", "std", "wasm-types-polyfill"], default-features = false }
bincode = { version = "1.3.3", default-features = false }
