[config]
default_to_workspace = false

[config.modify_core_tasks]
private = true
namespace = "default"

# Note - Relase mode: `cargo make mzoon start -- -r`
[tasks.mzoon]
description = "Run MZoon"
command = "cargo"
args = ["run", "--manifest-path", "../../crates/mzoon/Cargo.toml", "${@}"]
dependencies = ["default::install-wasm-pack"]

# Note - ${@} doesn't work in this context
# [tasks.mzoon]
# description = "Run MZoon"
# script_runner = "@duckscript"
# script = '''
# exec --fail-on-error cargo run --manifest-path "../../crates/mzoon/Cargo.toml" ${@}
# '''
# dependencies = ["default::install-wasm-pack"]


