[package]
name = "zoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.70"
blocks_macro = { path = "../blocks_macro" }
s_var_macro = { path = "../s_var_macro" }
update_macro = { path = "../update_macro" }
cache_macro = { path = "../cache_macro" }
call_tree_macro = { path = "../call_tree_macro" }

topo = { version = "0.13.2", features = [ "wasm-bindgen"] }
console_error_panic_hook = "0.1.6"

[dependencies.web-sys]
version = "0.3.48"
features = [
    "Document",
    "Element",
    "EventTarget",
    "Node",
    "NodeList",
    "Text",
    "Window",
]
