[package]
name = "zoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
wasm-bindgen = { version = "0.2.73", default_features = false }
console_error_panic_hook = { version = "0.1.6", default-features = false }
futures-signals = { version = "0.3.20", default-features = false }
dominator = { version = "0.5.16", default-features = false }

static_ref_macro = { path = "../static_ref_macro" }
paste = { version = "1.0.5", default-features = false }
once_cell = { version = "1.7.2", features = ["race", "alloc"], default-features = false }

wee_alloc = { version = "0.4.5", default-features = false }
enclose = { version = "1.1.8", default-features = false }
ufmt = { version = "0.1.0", features = ["std"], default_features = false }
lexical = { git = "https://github.com/Alexhuszagh/rust-lexical", rev = "7010efd", features = ["std"], default_features = false }

[dependencies.web-sys]
version = "0.3.50"
default-features = false
