[package]
name = "zoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.70"
console_error_panic_hook = { version = "0.1.6", default-features = false }
blocks_macro = { path = "../blocks_macro" }
s_var_macro = { path = "../s_var_macro" }
update_macro = { path = "../update_macro" }
cache_macro = { path = "../cache_macro" }
cmp_macro = { path = "../cmp_macro" }
tracked_call_macro = { path = "../tracked_call_macro" }
# @TODO remove rand and getrandom?
uuid = { version = "0.8.2", features = ["v4", "wasm-bindgen"], default_features = false }
# slotmap = { version = "1.0.3", default_features = false }
griddle = { version = "0.4.1", features = ["ahash", "inline-more", "ahash-compile-time-rng" ] }
ahash = { version = "0.7.2" }

once_cell = { version = "1.7.2" }
futures-signals = {version = "0.3.19" }

[dependencies.web-sys]
version = "0.3.48"
features = [
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "Node",
    "NodeList",
    "Text",
    "Window",
]
default-features = false
