[package]
name = "zoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
wasm-bindgen = { version = "0.2.73", default-features = false }
web-sys = { version = "0.3.50", default-features = false }
futures-signals = { version = "0.3.20", default-features = false }
dominator = { version = "0.5.16", default-features = false }
paste = { version = "1.0.5", default-features = false }

static_ref_macro = { path = "../static_ref_macro", optional = true }
once_cell = { version = "1.7.2", features = ["race", "alloc"], default-features = false, optional = true }

console_error_panic_hook = { version = "0.1.6", default-features = false, optional = true }
wee_alloc = { version = "0.4.5", default-features = false, optional = true }
enclose = { version = "1.1.8", default-features = false, optional = true }

ufmt = { version = "0.1.0", features = ["std"], default-features = false, optional = true }
lexical = { git = "https://github.com/Alexhuszagh/rust-lexical", rev = "7010efd", features = ["std"], default-features = false, optional = true }

[features]
default = ["static_ref", "panic_hook", "alloc", "clone"]
static_ref = ["static_ref_macro", "once_cell"]
panic_hook = ["console_error_panic_hook"]
alloc = ["wee_alloc"]
clone = ["enclose"]
fmt = ["ufmt", "lexical"]
